# Generated by Django 4.1 on 2022-08-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='store/files/')),
            ],
        ),
    ]
