# Generated by Django 4.1 on 2022-08-09 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_rename_file_fileupload_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
