# Generated by Django 4.1 on 2022-08-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_fileupload_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='fileurl',
            field=models.CharField(default='fufdydyd', max_length=100),
            preserve_default=False,
        ),
    ]
