# Generated by Django 4.1 on 2022-08-13 19:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_fileupload_fileurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='metadata',
            field=jsonfield.fields.JSONField(default='value'),
            preserve_default=False,
        ),
    ]
